const fs = require('fs').promises;
const path = require('path');
const crypto = require('crypto');

/**
 * Service for Bash script obfuscation and license injection
 */
class BashObfuscatorService {
  /**
   * Inject license validation code into bash script
   */
  async injectLicenseValidation(originalScript, licenseConfig) {
    const {
      productId,
      productName,
      apiUrl,
      welcomeMessage,
      supportContact,
      checkExpiry,
      checkActivation,
      checkMachine,
      showInfo
    } = licenseConfig;

    // Generate license validation template
    const validationCode = this.generateValidationTemplate({
      productId,
      productName,
      apiUrl,
      welcomeMessage,
      supportContact,
      checkExpiry: checkExpiry ? 'true' : 'false',
      checkActivation: checkActivation ? 'true' : 'false',
      checkMachine: checkMachine ? 'true' : 'false',
      showInfo: showInfo ? 'true' : 'false'
    });

    // Obfuscate original script
    const obfuscatedScript = await this.obfuscateScript(originalScript);

    // Combine validation + obfuscated script
    const protectedScript = validationCode + '\n\n' + obfuscatedScript;

    return protectedScript;
  }

  /**
   * Generate license validation template
   */
  generateValidationTemplate(config) {
    return `#!/bin/bash

#===============================================
# LICENSE PROTECTED SCRIPT
# Product: ${config.productName}
# Generated by: License Manager
# API: ${config.apiUrl}
# DO NOT MODIFY THIS SECTION
#===============================================

__PRODUCT_ID="${config.productId}"
__API_URL="${config.apiUrl}"
__WELCOME_MSG="${config.welcomeMessage}"
__SUPPORT_CONTACT="${config.supportContact}"
__CHECK_EXPIRY=${config.checkExpiry}
__CHECK_ACTIVATION=${config.checkActivation}
__CHECK_MACHINE=${config.checkMachine}
__SHOW_INFO=${config.showInfo}

# Colors for output
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m' # No Color

# Print header
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " \${__WELCOME_MSG}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Ask for license key
read -p "Enter your license key: " LICENSE_KEY

# Trim whitespace
LICENSE_KEY=\$(echo "\$LICENSE_KEY" | xargs)

# Validate not empty
if [ -z "\$LICENSE_KEY" ]; then
  echo -e "\${RED}✗ License key is required\${NC}"
  exit 1
fi

echo ""
echo "Validating license..."

# Get machine ID (for machine binding)
MACHINE_ID=\$(cat /etc/machine-id 2>/dev/null || hostid)

# Prepare JSON payload (without jq dependency)
JSON_PAYLOAD="{\\"licenseKey\\":\\"\$LICENSE_KEY\\",\\"productId\\":\\"\$__PRODUCT_ID\\",\\"machineId\\":\\"\$MACHINE_ID\\",\\"checkExpiry\\":\$__CHECK_EXPIRY,\\"checkActivation\\":\$__CHECK_ACTIVATION,\\"checkMachine\\":\$__CHECK_MACHINE}"

# Call API
RESPONSE=\$(curl -s -X POST "\$__API_URL" \\
  -H "Content-Type: application/json" \\
  -d "\$JSON_PAYLOAD" \\
  2>/dev/null)

# Check curl success
if [ \$? -ne 0 ]; then
  echo -e "\${RED}✗ Cannot connect to license server\${NC}"
  echo -e "  Please check your internet connection"
  echo -e "  Contact: \${__SUPPORT_CONTACT}"
  exit 1
fi

# Parse JSON response (without jq - using grep and sed)
IS_VALID=\$(echo "\$RESPONSE" | grep -o '"valid"[[:space:]]*:[[:space:]]*true')
ERROR_MSG=\$(echo "\$RESPONSE" | grep -o '"message"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/"message"[[:space:]]*:[[:space:]]*"\\(.*\\)"/\\1/')

# Check validation result
if [ -z "\$IS_VALID" ]; then
  echo -e "\${RED}✗ License validation failed\${NC}"
  if [ -n "\$ERROR_MSG" ]; then
    echo -e "  Reason: \$ERROR_MSG"
  fi
  echo -e "  Contact: \${__SUPPORT_CONTACT}"
  exit 1
fi

# Success!
echo -e "\${GREEN}✓ License valid\${NC}"

# Show license info if enabled
if [ "\$__SHOW_INFO" = "true" ]; then
  PRODUCT_NAME=\$(echo "\$RESPONSE" | grep -o '"productName"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/"productName"[[:space:]]*:[[:space:]]*"\\(.*\\)"/\\1/')
  CUSTOMER_NAME=\$(echo "\$RESPONSE" | grep -o '"customerName"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/"customerName"[[:space:]]*:[[:space:]]*"\\(.*\\)"/\\1/')
  EXPIRES_AT=\$(echo "\$RESPONSE" | grep -o '"expiresAt"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/"expiresAt"[[:space:]]*:[[:space:]]*"\\(.*\\)"/\\1/')

  [ -n "\$PRODUCT_NAME" ] && echo -e "\${BLUE}✓ Product: \$PRODUCT_NAME\${NC}"
  [ -n "\$CUSTOMER_NAME" ] && echo -e "\${BLUE}✓ Licensed to: \$CUSTOMER_NAME\${NC}"
  [ -n "\$EXPIRES_AT" ] && echo -e "\${BLUE}✓ Expires: \$EXPIRES_AT\${NC}"
fi

echo ""
echo "Starting script execution..."
echo ""

#===============================================
# ORIGINAL SCRIPT CONTENT (OBFUSCATED)
#===============================================
`;
  }

  /**
   * Obfuscate bash script using base64 encoding
   */
  async obfuscateScript(script) {
    // Remove shebang if exists
    let cleanScript = script.replace(/^#!\/bin\/bash\s*\n/, '');

    // Split into lines for obfuscation
    const lines = cleanScript.split('\n');
    const obfuscatedLines = [];

    for (const line of lines) {
      // Skip empty lines and comments
      if (!line.trim() || line.trim().startsWith('#')) {
        continue;
      }

      // Encode line to base64
      const encoded = Buffer.from(line).toString('base64');

      // Generate random variable name
      const varName = this.generateRandomVarName();

      // Create obfuscated line
      obfuscatedLines.push(`${varName}="${encoded}"`);
      obfuscatedLines.push(`eval "$(echo "$${varName}" | base64 -d)"`);
    }

    return obfuscatedLines.join('\n');
  }

  /**
   * Obfuscate bash script with level options
   */
  async obfuscateBashFile(inputPath, outputPath, level = 'medium', licenseConfig = null) {
    try {
      // Read original script
      const originalScript = await fs.readFile(inputPath, 'utf8');

      let finalScript;

      // If license injection enabled
      if (licenseConfig) {
        finalScript = await this.injectLicenseValidation(originalScript, licenseConfig);
      } else {
        // Just obfuscate without license
        const shebang = '#!/bin/bash\n\n';
        const obfuscated = await this.obfuscateScript(originalScript);
        finalScript = shebang + obfuscated;
      }

      // Write to output
      await fs.writeFile(outputPath, finalScript, 'utf8');

      // Make executable
      await fs.chmod(outputPath, 0o755);

      // Get file stats
      const originalSize = (await fs.stat(inputPath)).size;
      const obfuscatedSize = (await fs.stat(outputPath)).size;

      return {
        success: true,
        originalSize,
        obfuscatedSize,
        reduction: ((originalSize - obfuscatedSize) / originalSize * 100).toFixed(2)
      };
    } catch (error) {
      throw new Error(`Bash obfuscation error: ${error.message}`);
    }
  }

  /**
   * Generate random variable name for obfuscation
   */
  generateRandomVarName() {
    const chars = 'abcdefghijklmnopqrstuvwxyz';
    const nums = '0123456789';
    let name = '_';

    // First char must be letter
    name += chars[Math.floor(Math.random() * chars.length)];

    // Next 3-5 chars can be letters or numbers
    const length = 3 + Math.floor(Math.random() * 3);
    for (let i = 0; i < length; i++) {
      const allChars = chars + nums;
      name += allChars[Math.floor(Math.random() * allChars.length)];
    }

    return name;
  }

  /**
   * Validate bash script syntax
   */
  async validateBashScript(filePath) {
    try {
      const { exec } = require('child_process');
      const { promisify } = require('util');
      const execAsync = promisify(exec);

      // Use bash -n to check syntax without executing
      await execAsync(`bash -n ${filePath}`);

      return { valid: true };
    } catch (error) {
      return {
        valid: false,
        error: error.message
      };
    }
  }

  /**
   * Calculate file hash
   */
  async calculateFileHash(filePath) {
    const fileBuffer = await fs.readFile(filePath);
    const hashSum = crypto.createHash('sha256');
    hashSum.update(fileBuffer);
    return hashSum.digest('hex');
  }
}

module.exports = new BashObfuscatorService();
